basePath: /
definitions:
  types.Priority:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  types.Tag:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  types.Todo:
    properties:
      id:
        type: string
      isDone:
        type: boolean
      tags:
        items:
          $ref: '#/definitions/types.Tag'
        type: array
      title:
        type: string
      todoExt:
        $ref: '#/definitions/types.TodoExt'
        description: TrackDateTimes `json:"trackDateTimes"`
      userId:
        type: string
    type: object
  types.TodoExt:
    properties:
      description:
        type: string
      id:
        type: string
      priority:
        $ref: '#/definitions/types.Priority'
      priorityId:
        type: integer
    type: object
  types.User:
    properties:
      id:
        type: string
      name:
        type: string
      todos:
        items:
          $ref: '#/definitions/types.Todo'
        type: array
    type: object
host: localhost:8001
info:
  contact:
    email: xxx@demo.com
    name: JB
    url: https://karatejb.blogspot.com/
  description: TODO API sample by Gin
  title: TODO API
  version: "1.0"
paths:
  /api/todo:
    delete:
      consumes:
      - application/json
      description: The handler to delete an TODO
      parameters:
      - description: The TODO to be deleted.
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/types.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity
      tags:
      - Todo
    post:
      consumes:
      - application/json
      description: The handler to add a new TODO
      parameters:
      - description: The new TODO to be created.
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/types.Todo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.Todo'
        "400":
          description: Bad Request
      tags:
      - Todo
    put:
      consumes:
      - application/json
      description: The handler to edit a TODO
      parameters:
      - description: The TODO to be edited.
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/types.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity
      tags:
      - Todo
  /api/todo/{id}:
    get:
      consumes:
      - application/json
      description: The handler for getting the TODO by Id
      parameters:
      - description: A TODO's Id.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Todo'
        "204":
          description: No Content
      tags:
      - Todo
  /api/todos:
    delete:
      consumes:
      - application/json
      description: The handler to delete TODOs by their Id
      parameters:
      - description: The TODOs to be deleted.
        in: body
        name: todo
        required: true
        schema:
          items:
            $ref: '#/definitions/types.Todo'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      tags:
      - Todos
    get:
      consumes:
      - application/json
      description: The handler to response the TODO list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Todo'
            type: array
        "204":
          description: No Content
      tags:
      - Todos
  /api/todos/search:
    get:
      consumes:
      - application/json
      description: The handler for searching the TODOs by Title and IsDone
      parameters:
      - description: Contained keyword for TODO's Title.
        in: query
        name: title
        type: string
      - default: false
        description: Matched value for TODO's IsDone.
        in: query
        name: isDone
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Todo'
            type: array
        "204":
          description: No Content
      tags:
      - Todos
  /api/user:
    delete:
      consumes:
      - application/json
      description: The handler to delete an exist User from User list
      parameters:
      - description: The User to be deleted.
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/types.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity
      tags:
      - User
    post:
      consumes:
      - application/json
      description: The handler to add a new User
      parameters:
      - description: The new User to be created.
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/types.User'
        "400":
          description: Bad Request
      tags:
      - User
    put:
      consumes:
      - application/json
      description: The handler to edit a User
      parameters:
      - description: The User to be edited.
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.Todo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity
      tags:
      - User
  /api/user/{id}:
    get:
      consumes:
      - application/json
      description: The handler for getting the User by Id
      parameters:
      - description: The User's Id.
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.User'
        "204":
          description: No Content
      tags:
      - User
swagger: "2.0"
